name: region_detector
description: Listen to user clicks and drag events over portions of your screen. Implement callbacks to handle pointer events over specific regions of your screen.
version: 0.0.1
homepage: https://github.com/Algure/focus_detector

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
